/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Document */
        post: operations["upload_document_api_v1_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/extractions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract Document */
        post: operations["extract_document_api_v1_documents__document_id__extractions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/extractions/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Extraction Run */
        get: operations["get_extraction_run_api_v1_documents__document_id__extractions__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/reviews/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Review Document */
        put: operations["review_document_api_v1_documents__document_id__reviews__run_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feature-flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feature Flags */
        get: operations["feature_flags_api_v1_feature_flags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fixtures/p3/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fixture Context */
        get: operations["fixture_context_api_v1_fixtures_p3_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inspections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Case */
        post: operations["create_case_api_v1_inspections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inspections/{inspection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_api_v1_inspections__inspection_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inspections/{inspection_id}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approval */
        post: operations["approval_api_v1_inspections__inspection_id__approvals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inspections/{inspection_id}/internal-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Internal Results */
        put: operations["internal_results_api_v1_inspections__inspection_id__internal_results_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inspections/{inspection_id}/retests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retest */
        post: operations["retest_api_v1_inspections__inspection_id__retests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inspections/{inspection_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revision */
        post: operations["revision_api_v1_inspections__inspection_id__revisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inspections/{inspection_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Case */
        post: operations["submit_case_api_v1_inspections__inspection_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intakes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Intake */
        post: operations["intake_api_v1_intakes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/local-auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Local Session */
        post: operations["local_session_api_v1_local_auth_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lots/{material_lot_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lot Trace */
        get: operations["lot_trace_api_v1_lots__material_lot_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/material-models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Material Models */
        get: operations["list_material_models_api_v1_material_models_get"];
        put?: never;
        /** Create Material Model */
        post: operations["create_material_model_api_v1_material_models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/material-models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Material Model */
        get: operations["get_material_model_api_v1_material_models__model_id__get"];
        /** Update Material Model */
        put: operations["update_material_model_api_v1_material_models__model_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Materials */
        get: operations["list_materials_api_v1_materials_get"];
        put?: never;
        /** Create Material */
        post: operations["create_material_api_v1_materials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials/{material_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Material */
        get: operations["get_material_api_v1_materials__material_id__get"];
        /** Update Material */
        put: operations["update_material_api_v1_materials__material_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spec-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Profiles */
        get: operations["list_profiles_api_v1_spec_profiles_get"];
        put?: never;
        /** Create Profile */
        post: operations["create_profile_api_v1_spec_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spec-profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_v1_spec_profiles__profile_id__get"];
        /** Update Profile */
        put: operations["update_profile_api_v1_spec_profiles__profile_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spec-profiles/{profile_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Versions */
        get: operations["list_versions_api_v1_spec_profiles__profile_id__versions_get"];
        put?: never;
        /** Create Version */
        post: operations["create_version_api_v1_spec_profiles__profile_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spec-versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Version */
        get: operations["get_version_api_v1_spec_versions__version_id__get"];
        /** Update Version */
        put: operations["update_version_api_v1_spec_versions__version_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spec-versions/{version_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Version */
        post: operations["activate_version_api_v1_spec_versions__version_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spec-versions/{version_id}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retire Version */
        post: operations["retire_version_api_v1_spec_versions__version_id__retire_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Suppliers */
        get: operations["list_suppliers_api_v1_suppliers_get"];
        put?: never;
        /** Create Supplier */
        post: operations["create_supplier_api_v1_suppliers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers/{supplier_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Supplier */
        get: operations["get_supplier_api_v1_suppliers__supplier_id__get"];
        /** Update Supplier */
        put: operations["update_supplier_api_v1_suppliers__supplier_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApprovalRequest */
        ApprovalRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "APPROVE" | "RETURN";
            /** Reason */
            reason?: string | null;
        };
        /** BoundingBox */
        BoundingBox: {
            /** Bottom */
            bottom: number;
            /** Left */
            left: number;
            /** Right */
            right: number;
            /** Top */
            top: number;
        };
        /** DocumentResponse */
        DocumentResponse: {
            /** Checksum Sha256 */
            checksum_sha256: string;
            /** Deduplicated */
            deduplicated: boolean;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Storage Key */
            storage_key: string;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            /** Code */
            code: string;
            /**
             * Correlation Id
             * Format: uuid
             */
            correlation_id: string;
            /** Message */
            message: string;
            /**
             * Schema Version
             * @constant
             */
            schema_version: "1.0";
        };
        /** ExtractionFieldResponse */
        ExtractionFieldResponse: {
            bbox: components["schemas"]["BoundingBox"];
            /** Confidence */
            confidence: string;
            /**
             * Field Id
             * Format: uuid
             */
            field_id: string;
            /** Field Key */
            field_key: string;
            /** Final Text */
            final_text?: string | null;
            /** Mapped Field Key */
            mapped_field_key?: string | null;
            /** Mapping Disposition */
            mapping_disposition?: ("MAP" | "UNMAPPED") | null;
            /** Ocr Text */
            ocr_text: string;
            /** Original Text */
            original_text: string;
            /** Page Number */
            page_number: number;
            /** Provenance */
            provenance?: {
                [key: string]: unknown;
            };
            /** Reason */
            reason?: string | null;
            /** Required */
            required: boolean;
            /** Review Reasons */
            review_reasons?: string[];
            /** Source */
            source?: ("ORIGINAL" | "OCR" | "MANUAL") | null;
            /** Source Field Key */
            source_field_key: string;
            /**
             * Status
             * @enum {string}
             */
            status: "REVIEW_REQUIRED" | "CONFIRMED";
        };
        /** ExtractionRunResponse */
        ExtractionRunResponse: {
            /** Conflicts */
            conflicts: {
                [key: string]: unknown;
            }[];
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Fields */
            fields: components["schemas"]["ExtractionFieldResponse"][];
            /** Provider Name */
            provider_name: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "REVIEW_REQUIRED" | "CONFIRMED";
            /** Version */
            version: number;
        };
        /** FieldReviewInput */
        FieldReviewInput: {
            /** Field Id */
            field_id?: string | null;
            /** Field Key */
            field_key: string;
            /** Final Text */
            final_text: string;
            /**
             * Logic Conflict
             * @default false
             */
            logic_conflict: boolean;
            /** Manual Text */
            manual_text?: string | null;
            /** Mapped Field Key */
            mapped_field_key?: string | null;
            /** Mapping Disposition */
            mapping_disposition?: ("MAP" | "UNMAPPED") | null;
            /** Reason */
            reason: string;
            /**
             * Source
             * @enum {string}
             */
            source: "ORIGINAL" | "OCR" | "MANUAL";
        };
        /** FixtureContextResponse */
        FixtureContextResponse: {
            /**
             * Fixture Only
             * @default true
             * @constant
             */
            fixture_only: true;
            /** Mapping Item Codes */
            mapping_item_codes: string[];
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /** Material Name */
            material_name: string;
            /**
             * Model Id
             * Format: uuid
             */
            model_id: string;
            /**
             * Spec Version Id
             * Format: uuid
             */
            spec_version_id: string;
            /**
             * Supplier Id
             * Format: uuid
             */
            supplier_id: string;
            /** Supplier Name */
            supplier_name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthEnvelope */
        HealthEnvelope: {
            /**
             * Status
             * @enum {string}
             */
            status: "live" | "ready";
        };
        /** InspectionCreateRequest */
        InspectionCreateRequest: {
            /**
             * Allocation Id
             * Format: uuid
             */
            allocation_id: string;
            /**
             * Extraction Run Id
             * Format: uuid
             */
            extraction_run_id: string;
        };
        /** InspectionResponse */
        InspectionResponse: {
            /**
             * Allocation Id
             * Format: uuid
             */
            allocation_id: string;
            /** Blockers */
            blockers: string[];
            /** Candidate Decision */
            candidate_decision: string;
            /** Final Decision */
            final_decision: string | null;
            /**
             * Inspection Id
             * Format: uuid
             */
            inspection_id: string;
            /** Judgments */
            judgments: components["schemas"]["JudgmentView"][];
            /**
             * Material Lot Id
             * Format: uuid
             */
            material_lot_id: string;
            /** Revision No */
            revision_no: number;
            /** Round No */
            round_no: number;
            /** Spec Snapshot */
            spec_snapshot: {
                [key: string]: unknown;
            };
            /**
             * Spec Version Id
             * Format: uuid
             */
            spec_version_id: string;
            /** Status */
            status: string;
            /** Version */
            version: number;
        };
        /** IntakeRequest */
        IntakeRequest: {
            /** Inbound No */
            inbound_no: string;
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /** Model Id */
            model_id?: string | null;
            /** Quantity */
            quantity: string;
            /** Quantity Unit */
            quantity_unit: string;
            /**
             * Receipt Date
             * Format: date
             */
            receipt_date: string;
            /**
             * Supplier Id
             * Format: uuid
             */
            supplier_id: string;
            /** Supplier Lot No */
            supplier_lot_no: string;
        };
        /** IntakeResponse */
        IntakeResponse: {
            /**
             * Allocation Id
             * Format: uuid
             */
            allocation_id: string;
            /**
             * Inbound Receipt Id
             * Format: uuid
             */
            inbound_receipt_id: string;
            /**
             * Material Lot Id
             * Format: uuid
             */
            material_lot_id: string;
            /** Version */
            version: number;
        };
        /** InternalResultItem */
        InternalResultItem: {
            /**
             * Spec Item Id
             * Format: uuid
             */
            spec_item_id: string;
            /** Values */
            values: string[];
        };
        /** InternalResultsRequest */
        InternalResultsRequest: {
            /** Results */
            results: components["schemas"]["InternalResultItem"][];
        };
        /** JudgmentView */
        JudgmentView: {
            /** Effective Decision */
            effective_decision: string;
            /** Hyc Reference Decision */
            hyc_reference_decision: string | null;
            /** Internal Decision */
            internal_decision: string | null;
            /** Item Code */
            item_code: string;
            /**
             * Spec Item Id
             * Format: uuid
             */
            spec_item_id: string;
            /** Supplier Decision */
            supplier_decision: string | null;
        };
        /** LineageRequest */
        LineageRequest: {
            /** Reason */
            reason: string;
        };
        /** LocalSessionRequest */
        LocalSessionRequest: {
            /**
             * Fixture Principal
             * @enum {string}
             */
            fixture_principal: "p3-inspector" | "p3-lead" | "p3-admin";
        };
        /** LocalSessionResponse */
        LocalSessionResponse: {
            /**
             * Actor Id
             * Format: uuid
             */
            actor_id: string;
            /**
             * Auth Label
             * @constant
             */
            auth_label: "P3 fixture local identity/session — not production authentication";
            /**
             * Role
             * @enum {string}
             */
            role: "INSPECTOR" | "LEAD" | "ADMIN";
            /** Session Handle */
            session_handle: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /** LotTraceResponse */
        LotTraceResponse: {
            /** Allocations */
            allocations: {
                [key: string]: unknown;
            }[];
            /** Audits */
            audits: {
                [key: string]: unknown;
            }[];
            /** Documents */
            documents: {
                [key: string]: unknown;
            }[];
            /** Identity Key */
            identity_key: string;
            /** Inspections */
            inspections: {
                [key: string]: unknown;
            }[];
            /**
             * Material Lot Id
             * Format: uuid
             */
            material_lot_id: string;
            /** Receipts */
            receipts: {
                [key: string]: unknown;
            }[];
        };
        /** MaterialCreateRequest */
        MaterialCreateRequest: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Default Unit */
            default_unit?: string | null;
            /** Material Code */
            material_code?: string | null;
            /** Name */
            name: string;
        };
        /** MaterialModelCreateRequest */
        MaterialModelCreateRequest: {
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /** Model Code */
            model_code?: string | null;
            /** Name */
            name: string;
        };
        /** MaterialModelResponse */
        MaterialModelResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Lock Version */
            lock_version: number;
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /** Model Code */
            model_code: string | null;
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MaterialModelUpdateRequest */
        MaterialModelUpdateRequest: {
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /** Model Code */
            model_code?: string | null;
            /** Name */
            name: string;
        };
        /** MaterialResponse */
        MaterialResponse: {
            /** Active */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Default Unit */
            default_unit: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Lock Version */
            lock_version: number;
            /** Material Code */
            material_code: string | null;
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MaterialUpdateRequest */
        MaterialUpdateRequest: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Default Unit */
            default_unit?: string | null;
            /** Material Code */
            material_code?: string | null;
            /** Name */
            name: string;
        };
        /** ModuleFeatureFlagsResponse */
        ModuleFeatureFlagsResponse: {
            /** Ncr Approver Module Enabled */
            ncr_approver_module_enabled: boolean;
            /** Ncr Attachment Module Enabled */
            ncr_attachment_module_enabled: boolean;
            /** Ncr Completion Date Module Enabled */
            ncr_completion_date_module_enabled: boolean;
            /** Ncr Report Module Enabled */
            ncr_report_module_enabled: boolean;
            /** Ncr Retest Module Enabled */
            ncr_retest_module_enabled: boolean;
        };
        /** ReviewRequest */
        ReviewRequest: {
            /**
             * Allocation Id
             * Format: uuid
             */
            allocation_id: string;
            /** Fields */
            fields: components["schemas"]["FieldReviewInput"][];
            /** Spec Version Id */
            spec_version_id?: string | null;
        };
        /** SpecProfileCreateRequest */
        SpecProfileCreateRequest: {
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /** Model Id */
            model_id?: string | null;
            /** Name */
            name: string;
            /** Supplier Id */
            supplier_id?: string | null;
        };
        /** SpecProfileResponse */
        SpecProfileResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Lock Version */
            lock_version: number;
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /** Model Id */
            model_id: string | null;
            /** Name */
            name: string;
            /** Supplier Id */
            supplier_id: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SpecProfileUpdateRequest */
        SpecProfileUpdateRequest: {
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /** Model Id */
            model_id?: string | null;
            /** Name */
            name: string;
            /** Supplier Id */
            supplier_id?: string | null;
        };
        /** SpecVersionCreateRequest */
        SpecVersionCreateRequest: {
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
            /** Effective To */
            effective_to?: string | null;
            /** Revision Reason */
            revision_reason?: string | null;
            /** Version */
            version: number;
        };
        /** SpecVersionResponse */
        SpecVersionResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
            /** Effective To */
            effective_to: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Lock Version */
            lock_version: number;
            /** Revision Reason */
            revision_reason: string | null;
            /**
             * Spec Profile Id
             * Format: uuid
             */
            spec_profile_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "DRAFT" | "ACTIVE" | "RETIRED";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** SpecVersionUpdateRequest */
        SpecVersionUpdateRequest: {
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
            /** Effective To */
            effective_to?: string | null;
            /** Revision Reason */
            revision_reason?: string | null;
            /** Version */
            version: number;
        };
        /** SupplierCreateRequest */
        SupplierCreateRequest: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Name */
            name: string;
            /** Supplier Code */
            supplier_code?: string | null;
        };
        /** SupplierResponse */
        SupplierResponse: {
            /** Active */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Lock Version */
            lock_version: number;
            /** Name */
            name: string;
            /** Supplier Code */
            supplier_code: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SupplierUpdateRequest */
        SupplierUpdateRequest: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Name */
            name: string;
            /** Supplier Code */
            supplier_code?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_document_api_v1_documents_post: {
        parameters: {
            query?: never;
            header: {
                "X-Filename": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_document_api_v1_documents__document_id__extractions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_extraction_run_api_v1_documents__document_id__extractions__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_document_api_v1_documents__document_id__reviews__run_id__put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                document_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feature_flags_api_v1_feature_flags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleFeatureFlagsResponse"];
                };
            };
        };
    };
    fixture_context_api_v1_fixtures_p3_context_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixtureContextResponse"];
                };
            };
        };
    };
    create_case_api_v1_inspections_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InspectionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_api_v1_inspections__inspection_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inspection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approval_api_v1_inspections__inspection_id__approvals_post: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "Idempotency-Key"?: string | null;
                "X-P3-Fault-At"?: string | null;
            };
            path: {
                inspection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    internal_results_api_v1_inspections__inspection_id__internal_results_put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                inspection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InternalResultsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retest_api_v1_inspections__inspection_id__retests_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inspection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revision_api_v1_inspections__inspection_id__revisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inspection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_case_api_v1_inspections__inspection_id__submit_post: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                inspection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    intake_api_v1_intakes_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntakeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    local_session_api_v1_local_auth_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocalSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lot_trace_api_v1_lots__material_lot_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_lot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotTraceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_material_models_api_v1_material_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialModelResponse"][];
                };
            };
        };
    };
    create_material_model_api_v1_material_models_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialModelCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialModelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_material_model_api_v1_material_models__model_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialModelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_material_model_api_v1_material_models__model_id__put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialModelUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialModelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_materials_api_v1_materials_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponse"][];
                };
            };
        };
    };
    create_material_api_v1_materials_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_material_api_v1_materials__material_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_material_api_v1_materials__material_id__put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_profiles_api_v1_spec_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecProfileResponse"][];
                };
            };
        };
    };
    create_profile_api_v1_spec_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecProfileCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_v1_spec_profiles__profile_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_api_v1_spec_profiles__profile_id__put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_api_v1_spec_profiles__profile_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecVersionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_version_api_v1_spec_profiles__profile_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecVersionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_api_v1_spec_versions__version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_version_api_v1_spec_versions__version_id__put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecVersionUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_version_api_v1_spec_versions__version_id__activate_post: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retire_version_api_v1_spec_versions__version_id__retire_post: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_suppliers_api_v1_suppliers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierResponse"][];
                };
            };
        };
    };
    create_supplier_api_v1_suppliers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_supplier_api_v1_suppliers__supplier_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supplier_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_supplier_api_v1_suppliers__supplier_id__put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                supplier_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthEnvelope"];
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
