from __future__ import annotations

from collections.abc import Callable
from datetime import UTC, datetime
from uuid import UUID, uuid4

import pytest
from sqlalchemy import create_engine, text

from hyc_api.contracts import BoundingBox, ExtractionCandidate, ExtractionValue, SourceReference

pytestmark = pytest.mark.postgres


class GeneratedLocalProvider:
    """Injection-only provider for generated bytes; it never reads source evidence."""

    def extract(
        self,
        document_id: str,
        source_reference: str,
        *,
        document_bytes: bytes | None = None,
    ) -> ExtractionCandidate:
        assert document_bytes is not None and document_bytes.startswith(b"%PDF-")
        reference = SourceReference(
            document_id=UUID(document_id),
            source_reference=source_reference,
            page_number=1,
            bbox=BoundingBox(left=0.1, top=0.1, right=0.9, bottom=0.2),
        )
        return ExtractionCandidate(
            schema_version="1.0",
            candidate_id=uuid4(),
            created_at=datetime.now(UTC),
            document=reference,
            provider_name="local-paddleocr",
            values=[
                ExtractionValue(
                    item_key="OCR_TEXT_0001",
                    raw_text="96.50",
                    normalized_value=None,
                    provenance=reference,
                    confidence=0.9,
                    review_required=True,
                    reading_order=1,
                    recipe_id="original",
                    variant_id="original-r0",
                    rotation_degrees=0,
                    deskew_millidegrees=0,
                    deskew_status="NOT_NEEDED",
                    perspective_corrected=False,
                    reason_codes=["HUMAN_REVIEW_REQUIRED"],
                ),
                ExtractionValue(
                    item_key="OCR_TEXT_0002",
                    raw_text="generated note",
                    normalized_value=None,
                    provenance=reference,
                    confidence=0.7,
                    review_required=True,
                    reading_order=2,
                    recipe_id="original",
                    variant_id="original-r0",
                    rotation_degrees=0,
                    deskew_millidegrees=0,
                    deskew_status="NOT_NEEDED",
                    perspective_corrected=False,
                    reason_codes=["LOW_CONFIDENCE"],
                ),
            ],
            review_required=True,
        )


class FailingLocalProvider:
    def extract(
        self,
        document_id: str,
        source_reference: str,
        *,
        document_bytes: bytes | None = None,
    ) -> ExtractionCandidate:
        del document_id, source_reference, document_bytes
        raise RuntimeError("generated provider failure")


def _local_run(p3, provider=None) -> tuple[dict[str, object], dict[str, object]]:
    marker = uuid4().hex
    intake = p3.intake(suffix=marker)
    original_enabled = p3.client.app.state.settings.local_ocr_enabled
    original_provider = p3.client.app.state.local_ocr_provider
    p3.client.app.state.settings.local_ocr_enabled = True
    p3.client.app.state.local_ocr_provider = provider or GeneratedLocalProvider()
    try:
        document = p3.client.post(
            "/api/v1/documents",
            content=f"%PDF-generated-{marker}".encode(),
            headers=p3.inspector
            | {"X-Filename": "generated.pdf", "Content-Type": "application/pdf"},
        )
        assert document.status_code == 201, document.text
        extraction = p3.client.post(
            f"/api/v1/documents/{document.json()['document_id']}/extractions",
            headers=p3.inspector,
        )
        return intake | document.json(), extraction.json() if extraction.status_code == 201 else {
            "status_code": extraction.status_code,
            "body": extraction.json(),
        }
    finally:
        p3.client.app.state.settings.local_ocr_enabled = original_enabled
        p3.client.app.state.local_ocr_provider = original_provider


def _review_fields(run: dict[str, object]) -> list[dict[str, object]]:
    fields = run["fields"]
    assert isinstance(fields, list)
    return [
        {
            "field_id": field["field_id"],
            "field_key": field["source_field_key"],
            "manual_text": None,
            "final_text": "96.50" if index == 0 else "generated note",
            "source": "OCR",
            "reason": "generated-only human review",
            "logic_conflict": False,
            "mapping_disposition": "MAP" if index == 0 else "UNMAPPED",
            "mapped_field_key": "CACL2_PURITY" if index == 0 else None,
        }
        for index, field in enumerate(fields)
    ]


def _confirm(p3, context: dict[str, object], run: dict[str, object], fields=None):
    return p3.client.put(
        f"/api/v1/documents/{context['document_id']}/reviews/{run['run_id']}",
        json={
            "allocation_id": context["allocation_id"],
            "spec_version_id": p3.context["spec_version_id"],
            "fields": fields if fields is not None else _review_fields(run),
        },
        headers=p3.inspector | {"If-Match": str(run["version"])},
    )


def test_pdf_without_local_flag_fails_closed_without_fixture_values(p3) -> None:
    document = p3.client.post(
        "/api/v1/documents",
        content=f"%PDF-generated-disabled-{uuid4().hex}".encode(),
        headers=p3.inspector | {"X-Filename": "generated.pdf", "Content-Type": "application/pdf"},
    )
    response = p3.client.post(
        f"/api/v1/documents/{document.json()['document_id']}/extractions",
        headers=p3.inspector,
    )
    assert response.status_code == 422
    assert response.json()["message"] == "LOCAL_OCR_DISABLED"
    assert "P3-SYNTH" not in response.text


def test_verified_pdf_bytes_override_octet_stream_and_deduplicated_headers(p3) -> None:
    payload = f"%PDF-generated-octet-{uuid4().hex}".encode()
    first = p3.client.post(
        "/api/v1/documents",
        content=payload,
        headers=p3.inspector
        | {"X-Filename": "mismatch.bin", "Content-Type": "application/octet-stream"},
    )
    assert first.status_code == 201, first.text
    disabled = p3.client.post(
        f"/api/v1/documents/{first.json()['document_id']}/extractions", headers=p3.inspector
    )
    assert disabled.status_code == 422
    assert disabled.json()["message"] == "LOCAL_OCR_DISABLED"
    assert "P3-SYNTH" not in disabled.text

    duplicate = p3.client.post(
        "/api/v1/documents",
        content=payload,
        headers=p3.inspector | {"X-Filename": "mismatch.txt", "Content-Type": "text/plain"},
    )
    assert duplicate.status_code == 200, duplicate.text
    assert duplicate.json()["document_id"] == first.json()["document_id"]
    engine = create_engine(p3.database_url)
    with engine.connect() as connection:
        row = connection.execute(
            text("SELECT document_type, media_type FROM documents WHERE id = :document_id"),
            {"document_id": first.json()["document_id"]},
        ).one()
    engine.dispose()
    assert row == ("COA_PDF", "application/pdf")

    original_enabled = p3.client.app.state.settings.local_ocr_enabled
    original_provider = p3.client.app.state.local_ocr_provider
    p3.client.app.state.settings.local_ocr_enabled = True
    p3.client.app.state.local_ocr_provider = GeneratedLocalProvider()
    try:
        enabled = p3.client.post(
            f"/api/v1/documents/{first.json()['document_id']}/extractions", headers=p3.inspector
        )
    finally:
        p3.client.app.state.settings.local_ocr_enabled = original_enabled
        p3.client.app.state.local_ocr_provider = original_provider
    assert enabled.status_code == 201, enabled.text
    assert enabled.json()["provider_name"] == "local-paddleocr"


def test_legacy_document_metadata_is_not_updated_and_verified_bytes_route_extraction(p3) -> None:
    payload = f"%PDF-legacy-metadata-{uuid4().hex}".encode()
    document = p3.client.post(
        "/api/v1/documents",
        content=payload,
        headers=p3.inspector | {"X-Filename": "legacy.pdf"},
    )
    assert document.status_code == 201, document.text
    engine = create_engine(p3.database_url)
    try:
        with engine.begin() as connection:
            connection.execute(text("SET LOCAL session_replication_role = replica"))
            connection.execute(
                text(
                    "UPDATE documents SET document_type = 'SYNTHETIC_COA', "
                    "media_type = 'application/octet-stream' WHERE id = :document_id"
                ),
                {"document_id": document.json()["document_id"]},
            )
        duplicate = p3.client.post(
            "/api/v1/documents",
            content=payload,
            headers=p3.inspector | {"X-Filename": "legacy-duplicate.bin"},
        )
        assert duplicate.status_code == 200, duplicate.text
        with engine.connect() as connection:
            assert connection.execute(
                text("SELECT document_type, media_type FROM documents WHERE id = :document_id"),
                {"document_id": document.json()["document_id"]},
            ).one() == ("SYNTHETIC_COA", "application/octet-stream")
        original_enabled = p3.client.app.state.settings.local_ocr_enabled
        original_provider = p3.client.app.state.local_ocr_provider
        p3.client.app.state.settings.local_ocr_enabled = True
        p3.client.app.state.local_ocr_provider = GeneratedLocalProvider()
        try:
            extraction = p3.client.post(
                f"/api/v1/documents/{document.json()['document_id']}/extractions",
                headers=p3.inspector,
            )
        finally:
            p3.client.app.state.settings.local_ocr_enabled = original_enabled
            p3.client.app.state.local_ocr_provider = original_provider
        assert extraction.status_code == 201, extraction.text
        assert extraction.json()["provider_name"] == "local-paddleocr"
    finally:
        engine.dispose()


def test_nonzero_pdf_marker_is_rejected_before_fake_provider_routing(p3) -> None:
    payload = b"generated leading bytes\x00%PDF-generated-" + uuid4().hex.encode()
    document = p3.client.post(
        "/api/v1/documents",
        content=payload,
        headers=p3.inspector | {"X-Filename": "leading-bytes.bin", "Content-Type": "text/plain"},
    )
    assert document.status_code == 422, document.text
    assert document.json()["message"] == "DOCUMENT_BYTES_UNSUPPORTED"


@pytest.mark.parametrize(
    "payload",
    [b"generated unknown bytes", b"\x89PNG\r\n\x1a\n", b"\xff\xd8\xff\xe0"],
    ids=["unknown", "png", "jpeg"],
)
def test_unknown_or_image_bytes_are_rejected_without_fixture_routing(p3, payload: bytes) -> None:
    response = p3.client.post(
        "/api/v1/documents",
        content=payload,
        headers=p3.inspector | {"X-Filename": "untrusted.bin", "Content-Type": "application/pdf"},
    )
    assert response.status_code == 422
    assert response.json()["code"] == "HTTP_ERROR"
    assert response.json()["message"] == "DOCUMENT_BYTES_UNSUPPORTED"
    assert "untrusted.bin" not in response.text


def test_provider_failure_leaves_no_partial_run_or_field(p3) -> None:
    engine = create_engine(p3.database_url)
    with engine.connect() as connection:
        before = connection.execute(text("SELECT count(*) FROM extraction_runs")).scalar_one()
    _context, failure = _local_run(p3, FailingLocalProvider())
    assert failure["status_code"] == 500
    with engine.connect() as connection:
        assert (
            connection.execute(text("SELECT count(*) FROM extraction_runs")).scalar_one() == before
        )
    engine.dispose()


def test_local_persistence_resume_and_explicit_review_create_only_mapped_supplier_result(
    p3,
) -> None:
    context, run = _local_run(p3)
    assert run["provider_name"] == "local-paddleocr"
    assert run["status"] == "REVIEW_REQUIRED"
    assert all(field["status"] == "REVIEW_REQUIRED" for field in run["fields"])
    assert "storage" not in str(run["fields"]).lower()

    resumed = p3.client.get(
        f"/api/v1/documents/{context['document_id']}/extractions/{run['run_id']}",
        headers=p3.inspector,
    )
    assert resumed.status_code == 200
    assert resumed.json() == run
    assert (
        p3.client.get(
            f"/api/v1/documents/{uuid4()}/extractions/{run['run_id']}",
            headers=p3.inspector,
        ).status_code
        == 404
    )

    review = _confirm(p3, context, run)
    assert review.status_code == 200, review.text
    reviewed = review.json()
    assert {field["mapping_disposition"] for field in reviewed["fields"]} == {"MAP", "UNMAPPED"}
    assert (
        next(field for field in reviewed["fields"] if field["mapping_disposition"] == "MAP")[
            "field_key"
        ]
        == "CACL2_PURITY"
    )

    created = p3.client.post(
        "/api/v1/inspections",
        json={"allocation_id": context["allocation_id"], "extraction_run_id": run["run_id"]},
        headers=p3.inspector | {"Idempotency-Key": f"local-ocr-{uuid4().hex}"},
    )
    assert created.status_code == 201, created.text
    engine = create_engine(p3.database_url)
    with engine.connect() as connection:
        rows = connection.execute(
            text(
                "SELECT sti.code, sr.normalized_value FROM supplier_results sr "
                "JOIN standard_test_items sti ON sti.id = sr.standard_test_item_id "
                "WHERE sr.inspection_case_id = :case"
            ),
            {"case": created.json()["inspection_id"]},
        ).all()
    engine.dispose()
    assert [(code, str(value)) for code, value in rows] == [("CACL2_PURITY", "96.500000000000")]


@pytest.mark.parametrize(
    "invalid",
    ["", " 1", "1 ", "1 kg", "1,0", "+1", "1e2", "NaN", "Infinity", 1, 1.0],
    ids=[
        "empty",
        "leading-space",
        "trailing-space",
        "unit",
        "comma",
        "plus",
        "exponent",
        "nan",
        "infinity",
        "integer",
        "float",
    ],
)
def test_noncanonical_mapped_values_reject_before_mutation(p3, invalid: object) -> None:
    context, run = _local_run(p3)
    fields = _review_fields(run)
    fields[0]["final_text"] = invalid
    rejected = _confirm(p3, context, run, fields)
    assert rejected.status_code == 422, rejected.text
    assert _confirm(p3, context, run).status_code == 200


@pytest.mark.parametrize(
    "invalid",
    ["1000000000000", "0.1234567890123"],
    ids=["thirteen-integer-digits", "thirteen-fractional-digits"],
)
def test_numeric_storage_bounds_reject_at_confirm_without_partial_mutation(
    p3, invalid: str
) -> None:
    context, run = _local_run(p3)
    fields = _review_fields(run)
    fields[0]["final_text"] = invalid
    rejected = _confirm(p3, context, run, fields)
    assert rejected.status_code == 422, rejected.text
    resumed = p3.client.get(
        f"/api/v1/documents/{context['document_id']}/extractions/{run['run_id']}",
        headers=p3.inspector,
    )
    assert resumed.status_code == 200
    assert resumed.json()["status"] == "REVIEW_REQUIRED"
    assert all(field["final_text"] is None for field in resumed.json()["fields"])
    assert _confirm(p3, context, run).status_code == 200


def _missing(fields: list[dict[str, object]]) -> None:
    fields.pop()


def _duplicate(fields: list[dict[str, object]]) -> None:
    fields[1] = dict(fields[0])


def _unknown_id(fields: list[dict[str, object]]) -> None:
    fields[0]["field_id"] = str(uuid4())


def _unknown_source(fields: list[dict[str, object]]) -> None:
    fields[0]["field_key"] = "OCR_TEXT_UNKNOWN"


def _unknown_target(fields: list[dict[str, object]]) -> None:
    fields[0]["mapped_field_key"] = "NOT_IN_CURRENT_SPEC"


def _duplicate_target(fields: list[dict[str, object]]) -> None:
    fields[1].update(mapping_disposition="MAP", mapped_field_key="CACL2_PURITY", final_text="0.10")


def _missing_disposition(fields: list[dict[str, object]]) -> None:
    fields[0]["mapping_disposition"] = None


@pytest.mark.parametrize(
    "mutate",
    [
        _missing,
        _duplicate,
        _unknown_id,
        _unknown_source,
        _unknown_target,
        _duplicate_target,
        _missing_disposition,
    ],
    ids=[
        "missing",
        "duplicate",
        "unknown-id",
        "unknown-source",
        "out-of-spec",
        "duplicate-target",
        "missing-disposition",
    ],
)
def test_mapping_identity_and_completeness_failures_leave_zero_partial_mutation(
    p3, mutate: Callable[[list[dict[str, object]]], None]
) -> None:
    context, run = _local_run(p3)
    fields = _review_fields(run)
    mutate(fields)
    rejected = _confirm(p3, context, run, fields)
    assert rejected.status_code == 422, rejected.text
    assert _confirm(p3, context, run).status_code == 200


def test_review_api_rejects_more_than_500_fields_at_contract_boundary(p3) -> None:
    context = p3.reviewed_extraction()
    field = {
        "field_key": "LOT_NO",
        "manual_text": None,
        "final_text": "P3-SYNTH-LOT-20260801",
        "source": "OCR",
        "reason": "generated review",
        "logic_conflict": False,
    }
    response = p3.client.put(
        f"/api/v1/documents/{context['document_id']}/reviews/{context['run_id']}",
        json={"allocation_id": context["allocation_id"], "fields": [field] * 501},
        headers=p3.inspector | {"If-Match": str(context["version"])},
    )
    assert response.status_code == 422


@pytest.mark.parametrize(
    "invalid",
    ["96.50 ", "1000000000000", "0.1234567890123"],
    ids=["noncanonical", "thirteen-integer-digits", "thirteen-fractional-digits"],
)
def test_failed_inspection_validation_releases_idempotency_reservation_after_repair(
    p3, invalid: str
) -> None:
    context, run = _local_run(p3)
    assert _confirm(p3, context, run).status_code == 200
    engine = create_engine(p3.database_url)
    try:
        with engine.begin() as connection:
            connection.execute(text("SET LOCAL session_replication_role = replica"))
            connection.execute(
                text(
                    "UPDATE extraction_field_reviews SET final_text = :invalid "
                    "WHERE extraction_run_id = :run AND field_key = 'CACL2_PURITY'"
                ),
                {"invalid": invalid, "run": run["run_id"]},
            )
        key = f"retry-after-repair-{uuid4().hex}"
        payload = {"allocation_id": context["allocation_id"], "extraction_run_id": run["run_id"]}
        failed = p3.client.post(
            "/api/v1/inspections",
            json=payload,
            headers=p3.inspector | {"Idempotency-Key": key},
        )
        assert failed.status_code == 422, failed.text
        with engine.connect() as connection:
            assert (
                connection.execute(
                    text("SELECT count(*) FROM idempotency_keys WHERE key = :key"), {"key": key}
                ).scalar_one()
                == 0
            )
        with engine.begin() as connection:
            connection.execute(text("SET LOCAL session_replication_role = replica"))
            connection.execute(
                text(
                    "UPDATE extraction_field_reviews SET final_text = '96.50' "
                    "WHERE extraction_run_id = :run AND field_key = 'CACL2_PURITY'"
                ),
                {"run": run["run_id"]},
            )
        retried = p3.client.post(
            "/api/v1/inspections",
            json=payload,
            headers=p3.inspector | {"Idempotency-Key": key},
        )
        assert retried.status_code == 201, retried.text
    finally:
        engine.dispose()


def test_completed_idempotency_conflict_wins_before_invalid_resource_validation(p3) -> None:
    context = p3.reviewed_extraction()
    key = f"completed-key-priority-{uuid4().hex}"
    payload = {"allocation_id": context["allocation_id"], "extraction_run_id": context["run_id"]}
    first = p3.client.post(
        "/api/v1/inspections", json=payload, headers=p3.inspector | {"Idempotency-Key": key}
    )
    assert first.status_code == 201, first.text
    conflict = p3.client.post(
        "/api/v1/inspections",
        json={"allocation_id": str(uuid4()), "extraction_run_id": str(uuid4())},
        headers=p3.inspector | {"Idempotency-Key": key},
    )
    assert conflict.status_code == 409
    assert conflict.json()["message"] == "Idempotency key request conflict"


def test_extract_document_rejects_new_run_after_confirmation(p3) -> None:
    context, run = _local_run(p3)
    assert _confirm(p3, context, run).status_code == 200
    repeated = p3.client.post(
        f"/api/v1/documents/{context['document_id']}/extractions", headers=p3.inspector
    )
    assert repeated.status_code == 409
    assert repeated.json()["message"] == "DOCUMENT_EXTRACTION_ALREADY_CONFIRMED"


def test_stale_selected_spec_rejects_without_mutation(p3) -> None:
    context, run = _local_run(p3)
    response = p3.client.put(
        f"/api/v1/documents/{context['document_id']}/reviews/{run['run_id']}",
        json={
            "allocation_id": context["allocation_id"],
            "spec_version_id": str(uuid4()),
            "fields": _review_fields(run),
        },
        headers=p3.inspector | {"If-Match": str(run["version"])},
    )
    assert response.status_code == 422
    assert _confirm(p3, context, run).status_code == 200


@pytest.mark.parametrize("tamper", ["decimal", "mapping", "spec"])
def test_create_inspection_independently_rejects_tampered_confirmed_records(
    p3, tamper: str
) -> None:
    context, run = _local_run(p3)
    assert _confirm(p3, context, run).status_code == 200
    engine = create_engine(p3.database_url)
    with engine.begin() as connection:
        before = connection.execute(text("SELECT count(*) FROM inspection_cases")).scalar_one()
        connection.execute(text("SET LOCAL session_replication_role = replica"))
        if tamper == "decimal":
            connection.execute(
                text(
                    "UPDATE extraction_field_reviews SET final_text = '96.50 ' "
                    "WHERE extraction_run_id = :run AND field_key = 'CACL2_PURITY'"
                ),
                {"run": run["run_id"]},
            )
        elif tamper == "mapping":
            connection.execute(
                text(
                    "UPDATE extraction_field_reviews SET field_key = 'NOT_IN_CURRENT_SPEC' "
                    "WHERE extraction_run_id = :run AND field_key = 'CACL2_PURITY'"
                ),
                {"run": run["run_id"]},
            )
        else:
            connection.execute(
                text(
                    "UPDATE extraction_runs SET candidate_payload = "
                    "jsonb_set(candidate_payload::jsonb, '{review,spec_version_id}', "
                    "to_jsonb(CAST(:spec AS text)))::json WHERE id = :run"
                ),
                {"run": run["run_id"], "spec": str(uuid4())},
            )
    response = p3.client.post(
        "/api/v1/inspections",
        json={"allocation_id": context["allocation_id"], "extraction_run_id": run["run_id"]},
        headers=p3.inspector | {"Idempotency-Key": f"tamper-{uuid4().hex}"},
    )
    assert response.status_code == 422, response.text
    with engine.connect() as connection:
        assert (
            connection.execute(text("SELECT count(*) FROM inspection_cases")).scalar_one() == before
        )
    engine.dispose()
